# Generated by Django 3.2.7 on 2021-09-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_part_of_speech'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.CharField(max_length=50)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_translate', to='words.word')),
            ],
        ),
    ]
