# Generated by Django 3.2.7 on 2021-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_wordtranslate'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('rus', 'Russian'), ('eng', 'English')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
