# Generated by Django 3.2.7 on 2021-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='part_of_speech',
        ),
        migrations.AddField(
            model_name='wordtranslate',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'noun'), ('pronoun', 'pronoun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('preposition', 'preposition'), ('conjunction.', 'conjunction'), ('interjection', 'interjection')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
